runtime: python39
instance_class: F2
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
env_variables:
  MY_VARIABLE: "venv"
automatic_scaling:
  # target_cpu_utilization: 0.65

