# Generated by Django 4.2.6 on 2023-10-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('faculté', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarité.faculté')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, upload_to='uploads/')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('nom_de_famille', models.CharField(max_length=255)),
                ('dossier', models.FileField(default=None, upload_to='uploads/')),
                ('filière', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarité.filière')),
            ],
        ),
    ]
