# Generated by Django 4.2.6 on 2023-10-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarité', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='dossier',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
