# Generated by Django 4.2.6 on 2023-10-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scolarité', '0002_alter_etudiant_dossier_alter_etudiant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AlterModelOptions(
            name='faculté',
            options={'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterModelOptions(
            name='filière',
            options={'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='dossier',
            field=models.FileField(default=None, upload_to='uploads/', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filière',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarité.filière', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.FileField(default=None, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_de_famille',
            field=models.CharField(max_length=255, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='faculté',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='filière',
            name='faculté',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scolarité.faculté', verbose_name='Faculté'),
        ),
        migrations.AlterField(
            model_name='filière',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
